controller_list:
  - name: fake_right_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_ul_r_shoulder_pitch
      - Joint_ul_r_shoulder_roll
      - Joint_ul_r_shoulder_yaw
      - Joint_ul_r_elbow_pitch
      - Joint_ul_r_wrist_yaw
      - Joint_ul_r_wrist_pitch
  - name: fake_left_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_ul_l_shoulder_pitch
      - Joint_ul_l_shoulder_roll
      - Joint_ul_l_shoulder_yaw
      - Joint_ul_l_elbow_pitch
      - Joint_ul_l_wrist_yaw
      - Joint_ul_l_wrist_pitch
  - name: fake_head_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_Neck_Pitch_1
      - Joint_Neck_Yaw_1
  - name: fake_torso_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_DownLimb_Pitch_1
      - Joint_DownLimb_Pitch_2
      - Joint_DownLimb_Pitch_3
      - Joint_DownLimb_Yaw_1
  - name: fake_dual_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - Joint_ul_l_shoulder_pitch
      - Joint_ul_l_shoulder_roll
      - Joint_ul_l_shoulder_yaw
      - Joint_ul_l_elbow_pitch
      - Joint_ul_l_wrist_yaw
      - Joint_ul_l_wrist_pitch
      - Joint_ul_r_shoulder_pitch
      - Joint_ul_r_shoulder_roll
      - Joint_ul_r_shoulder_yaw
      - Joint_ul_r_elbow_pitch
      - Joint_ul_r_wrist_yaw
      - Joint_ul_r_wrist_pitch
initial:  # Define initial robot poses per group
  - group: right_arm
    pose: forward
  - group: left_arm
    pose: home
  - group: head
    pose: home
  - group: torso
    pose: stood_up

#    pose: laid_back